services:
  traefik:
    image: "traefik:${TRAEFIK_VERSION}"
    container_name: "traefik"
    env_file:
      - .env
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"
      - "--entryPoints.web.address=:80"
      - "--api.insecure=false"
      - "--api.dashboard=true"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.websecure.http.tls=true"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
      
      # Let's Encrypt configuration
      - "--certificatesresolvers.le.acme.email=${TLS_EMAIL_ADDRESS}"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    labels:

      # Authentication middleware
      - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_DASHBOARD_USER}:${TRAEFIK_DASHBOARD_PASSWORD_HASH}"
     
      # Dashboard router
      - "traefik.http.routers.dashboard.rule=Host(traefik.${DOMAIN_NAME})"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=le"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"

  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    restart: unless-stopped
    networks:
      - proxy
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN_NAME}`)"

      # Security Middleware 
      - "traefik.http.middlewares.secure-headers.headers.frameDeny=true"
      - "traefik.http.middlewares.secure-headers.headers.sslRedirect=true"
      - "traefik.http.middlewares.secure-headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.secure-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.secure-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.secure-headers.headers.stsPreload=true"
      - "traefik.http.middlewares.secure-headers.headers.stsSeconds=31536000"
     
      # Apply middlewares to router
      - "traefik.http.routers.whoami.middlewares=secure-headers"
      
      # Add TLS
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.certresolver=le"

  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: "postgres"
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_USER: ${POSTGRES_DB_USERNAME}
    networks: 
      - proxy
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes: 
      - postgres_data:/var/lib/postgresql

  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_USER: ${MYSQL_DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: false
    ports:
      - "${MYSQL_DB_PORT}:3306"
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks: 
      - proxy
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    restart: unless-stopped
    env_file:
      - .env
    command: redis-server --appendonly yes --requirepass "${REDIS_DB_PASSWORD}"
    ports:
      - "${REDIS_DB_PORT}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_DB_PASSWORD}", "ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: 
      - proxy
    volumes: 
      - redis_data:/data

networks:
  proxy:
    name: proxy

volumes:
  postgres_data:
  mysql_data:
  redis_data: